# -*- coding: utf-8 -*-
"""realtimeobjectdetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NF1w5cGjc1zrzNuI-fg-VWLpA9PyBfbK
"""

!pip install opencv-python
!pip install opencv-python-headless

!wget https://raw.githubusercontent.com/chuanqi305/MobileNet-SSD/master/deploy.prototxt -O MobileNetSSD_deploy.prototxt
!wget https://raw.githubusercontent.com/chuanqi305/MobileNet-SSD/master/mobilenet_iter_73000.caffemodel -O MobileNetSSD_deploy.caffemodel

import cv2

# Load the Caffe model
net = cv2.dnn.readNetFromCaffe("MobileNetSSD_deploy.prototxt",
                               "MobileNetSSD_deploy.caffemodel")

# Define class labels the model can detect
CLASSES = ["background", "aeroplane", "bicycle", "bird", "boat",
           "bottle", "bus", "car", "cat", "chair", "cow", "diningtable",
           "dog", "horse", "motorbike", "person", "pottedplant",
           "sheep", "sofa", "train", "tvmonitor"]

from google.colab import files
uploaded = files.upload()

video_path = next(iter(uploaded))

import numpy as np
from IPython.display import display, Image
import cv2

cap = cv2.VideoCapture(video_path)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    (h, w) = frame.shape[:2]
    blob = cv2.dnn.blobFromImage(cv2.resize(frame, (300, 300)),
                                 0.007843, (300, 300), 127.5)

    net.setInput(blob)
    detections = net.forward()

    # Loop over the detections
    for i in range(detections.shape[2]):
        confidence = detections[0, 0, i, 2]

        if confidence > 0.5:  # Adjust threshold if needed
            idx = int(detections[0, 0, i, 1])
            label = CLASSES[idx]
            print(f"Detected: {label} ({confidence * 100:.2f}%)")

            box = detections[0, 0, i, 3:7] * np.array([w, h, w, h])
            (startX, startY, endX, endY) = box.astype("int")

            cv2.rectangle(frame, (startX, startY), (endX, endY), (0, 255, 0), 2)
            y = startY - 10 if startY > 20 else startY + 20
            cv2.putText(frame, f"{label}: {confidence*100:.2f}%", (startX, y),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 2)

    # Save and display the frame in Colab
    frame = cv2.resize(frame, (640, 480))
    cv2.imwrite("frame.jpg", frame)
    display(Image("frame.jpg"))

cap.release()
cv2.destroyAllWindows()